import Head from "next/head";
import ContactForm from "../components/contactForm/contactForm";
import Footer from "../components/shared/footer/footer";
import Nav from "../components/shared/nav/nav";

const Contact = () => {
    return(
        <>
            <Head>
                <title>Maria Morán</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Nav actual='contact' />
            <main className='page'>
                <ContactForm />
            </main>
            <Footer />
        </>
    )
}

export default Contact;