import Head from 'next/head';
import Project from '../components/project/project';
import Footer from '../components/shared/footer/footer';
import Nav from '../components/shared/nav/nav';


const WebProjects = () => {
    return(
        <div>
            <Head>
                <title>Maria Morán</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Nav />
            <main className='page'>
                <Project />
            </main>
            <Footer />
        </div>
    )
}

export default WebProjects;