import useTranslation from 'next-translate/useTranslation';
import Head from 'next/head';
import ProjectsLayout from "../components/layouts/projectsLayout/projectsLayout";
import Footer from '../components/shared/footer/footer';
import Nav from '../components/shared/nav/nav';
import { getDevice } from '../hooks/size';


const WebProjects = () => {
    const {t} = useTranslation();
    const device = getDevice();
    const list = [
        {title: 'TIM BROWN', description:'A book cover designed for Tim Brown’s new release, ‘Change’s', image: '/graphic-design/desktop/image-change.jpg'},
        {title: 'BOXED WATER', description:'A simple packaging concept made for Boxed Water', image: '/graphic-design/desktop/image-boxed-water.jpg'},
        {title: 'SCIENCE !', description:'A poster made in collaboration with the Federal Art Project', image: '/graphic-design/desktop/image-science.jpg'},
    ]
    const links = [
        {title: t("common:web_development"), image:`/home/${device}/image-web-design.jpg`, link:'/web-projects'},
        {title: t("common:app_development"), image:`/home/${device}/image-app-design.jpg`, link:'/app-projects'},
    ]
    return(
        <div>
            <Head>
                <title>Maria Morán</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Nav />
            <main className='page'>
                <ProjectsLayout 
                    title={'Resources'} 
                    subtitle={'We build websites that serve as powerful marketing tools and bring memorable brand experiences.'} 
                    list={list} 
                    links={links}
                />
            </main>
            <Footer />
        </div>
    )
}

export default WebProjects;